--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: wellnessdb; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA wellnessdb;


ALTER SCHEMA wellnessdb OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: wellnessdb; Owner: postgres
--

CREATE TABLE wellnessdb.users (
    id bigint NOT NULL,
    studentnumber character varying(40) NOT NULL,
    firstname character varying(120) NOT NULL,
    surname character varying(120) NOT NULL,
    email character varying(120) NOT NULL,
    phone character varying(15) NOT NULL,
    password character varying NOT NULL
);


ALTER TABLE wellnessdb.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: wellnessdb; Owner: postgres
--

ALTER TABLE wellnessdb.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wellnessdb.users_id_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: users; Type: TABLE DATA; Schema: wellnessdb; Owner: postgres
--

COPY wellnessdb.users (id, studentnumber, firstname, surname, email, phone, password) FROM stdin;
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: wellnessdb; Owner: postgres
--

SELECT pg_catalog.setval('wellnessdb.users_id_seq', 0, true);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: wellnessdb; Owner: postgres
--

ALTER TABLE ONLY wellnessdb.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- Name: users users_pk_2; Type: CONSTRAINT; Schema: wellnessdb; Owner: postgres
--

ALTER TABLE ONLY wellnessdb.users
    ADD CONSTRAINT users_pk_2 UNIQUE (studentnumber);


--
-- PostgreSQL database dump complete
--

